# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LingoClash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LingoClash

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod "PromiseKit", "~> 6.8"

end
